---
- name: Create legal directory
  file:
    state: directory
    path: "{{ artemis_legal_path }}"
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"
    mode: "755"
  become: true
  become_user: "{{ artemis_user }}"

- name: Copy privacy_statements into legal directory
  copy:
    src: privacy/ # KEEP THE /
    dest: "{{ artemis_legal_path }}"
    owner: "{{ artemis_user }}"
    group: "{{ artemis_user }}"
    mode: "644"
  become: true
  become_user: "{{ artemis_user }}"

- name: Copy imprints into legal directory
  copy:
    src: imprints/ # KEEP THE /
    dest: "{{ artemis_legal_path }}"
    owner: "{{ artemis_user }}"
    group: "{{ artemis_user }}"
    mode: "644"
  become: true
  become_user: "{{ artemis_user }}"
