- name: Check if python3-pip is installed
  command: dpkg-query -l python3-pip
  register: pip_check
  ignore_errors: true 

- name: Install python3-pip
  become: true
  apt:
    name: python3-pip
  when: pip_check.stdout.find('no packages found') == -1

- name: Install python docker module
  become: true
  pip:
    name: docker

- name: Create config directory
  become: true
  file:
    path: /opt/gitlab/config
    state: directory

- name: Create data directory
  become: true
  file:
    path: /opt/gitlab/data
    state: directory

- name: Create logs directory
  become: true
  file:
    path: /opt/gitlab/logs
    state: directory

- name: Copy gitlab config
  become: true
  template:
    src: gitlab.rb.j2
    dest: /opt/gitlab/config/gitlab.rb
    mode: 0644
  register: copyConf

- name: Pull image from docker hub
  become: true
  community.docker.docker_container:
    name: gitlab-ce
    state: present
    image: "gitlab/gitlab-ce:latest"


- name: Start gitlab container
  become: true
  community.docker.docker_container:
    name: gitlab
    image: "gitlab/gitlab-ce:latest"
    state: started
    recreate: true
    restart_policy: unless-stopped
    env:
    volumes:
      - /opt/gitlab/data:/var/opt/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/config:/etc/gitlab
    ports:
      - "8081:80"
      - "8443:22"
    env:
        GITLAB_ROOT_PASSWORD: "jFDguYU6$qE#YvkR"

#- name: Reconfigure Gitlab
#  become: true
#  shell: "docker exec gitlab gitlab-ctl reconfigure"
#  changed_when: copyConf.changed

- name: Wait for Gitlab to come up
  uri:
    url: "http://127.0.0.1:8081"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5