- name: Ensure locale en_US.UTF-8 exists
  become: true
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ensure locale is set in /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^LC_ALL='
    line: LC_ALL=en_US.UTF-8
    state: present

- name: Ensure language is set in /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^LANG='
    line: LANG=en_US.UTF-8
    state: present

- name: Install Artemis requirements
  become: true
  apt:
    name:
      - git
      - mysql-client
      - graphviz
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Create artemis directory
  become: true
  file:
    path: "{{ artemis_working_directory }}"
    state: directory
    mode: '775'

- name: Set permissions for artemis directory
  become: true
  file:
    path: "{{ artemis_working_directory }}"
    state: directory
    recurse: no
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"

- name: Create artemis ssh key directory
  become: true
  file:
    path: "{{ artemis_ssh_key_path }}"
    state: directory
  when: artemis_ssh_priv_key_value is not none and artemis_ssh_key_path is not none and artemis_ssh_key_path != ""

- name: Create artemis data-export directory
  become: true
  become_user: "{{ artemis_user_name }}"
  file:
    path: "{{ artemis_data_export_path }}"
    state: directory
    mode: '775'
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  when: artemis_data_export_path is not none and artemis_data_export_path != "" and artemis_computed_is_core_node

- name: Set permissions for artemis data-export directory
  become: true
  file:
    path: "{{ artemis_data_export_path }}"
    state: directory
    recurse: true
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  when: artemis_data_export_path is not none and artemis_data_export_path != "" and artemis_computed_is_core_node

- name: Add artemis user to docker group
  become: true
  user:
    name: "{{ artemis_user_name }}"
    groups: docker
    append: yes
  when: 
    - continuous_integration.localci is defined
    - is_build_agent is defined and (is_build_agent | bool)

- include_tasks: generate_ssh_keys.yml
  when:
    - version_control.localvc is defined and version_control.localvc is not none
    - version_control.localvc.ssh_key_path is defined and version_control.localvc.ssh_key_path|length > 0

- name: Copy artemis.service systemd configuration
  become: true
  template:
    src: artemis.service.j2
    dest: "/etc/systemd/system/artemis.service"
    mode: "644"

- name: Enable artemis service
  become: true
  systemd:
    daemon_reload: yes
    name: artemis
    enabled: yes
    masked: no
