---
- name: Ensure locale en_US.UTF-8 exists
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ensure locale is set in /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: "^LC_ALL="
    line: LC_ALL=en_US.UTF-8
    state: present

- name: Ensure language is set in /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: "^LANG="
    line: LANG=en_US.UTF-8
    state: present

- name: Install Artemis requirements
  become: true
  apt:
    name:
      - git
      - mysql-client
      - graphviz
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create artemis directory
  become: true
  file:
    path: "{{ artemis_working_directory }}"
    state: directory
    mode: "775"

- name: Set permissions for artemis directory
  become: true
  file:
    path: "{{ artemis_working_directory }}"
    state: directory
    recurse: false
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"

- name: Create artemis ssh key directory
  become: true
  file:
    path: "{{ artemis_ssh_key_path }}"
    state: directory
  when: artemis_ssh_priv_key_value is not none and artemis_ssh_key_path is not none and artemis_ssh_key_path != ""

- name: Create artemis data-export directory
  become: true
  become_user: "{{ artemis_user_name }}"
  file:
    path: "{{ artemis_data_export_path }}"
    state: directory
    mode: "775"
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  when: artemis_data_export_path is not none and artemis_data_export_path != "" and artemis_computed_is_core_node

- name: Set permissions for artemis data-export directory
  become: true
  file:
    path: "{{ artemis_data_export_path }}"
    state: directory
    recurse: true
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  when: artemis_data_export_path is not none and artemis_data_export_path != "" and artemis_computed_is_core_node

- name: Create tmp directory
  become: true
  file:
    path: "{{ artemis_tmp_directory }}"
    state: directory
    mode: "775"
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  when: if artemis_tmp_directory is defined and artemis_tmp_directory is not none and artemis_tmp_directory

- name: Turn the tmp directory into a tmpfs
  become: true
  ansible.posix.mount:
    path: "{{ artemis_tmp_directory }}"
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noatime,nosuid,nodev,noexec,mode=1777,size=1G
    state: mounted
  when: if artemis_tmp_directory is defined and artemis_tmp_directory is not none and artemis_tmp_directory

- name: Add artemis user to docker group
  become: true
  user:
    name: "{{ artemis_user_name }}"
    groups: docker
    append: true
  when:
    - continuous_integration.localci is defined
    - is_build_agent is defined and (is_build_agent | bool)

- include_tasks: generate_ssh_keys.yml
  when:
    - version_control.localvc is defined and version_control.localvc is not none
    - version_control.localvc.ssh_key_path is defined and version_control.localvc.ssh_key_path|length > 0

- name: Set entropy bits override for mmap randomization
  ansible.posix.sysctl:
    name: vm.mmap_rnd_bits
    value: "{{ entropy_bits_override }}"
    state: present
    reload: true
  become: true
  when:
    - continuous_integration.localci.is_build_agent is defined
    - continuous_integration.localci.is_build_agent
    - entropy_bits_override is defined and entropy_bits_override is defined and entropy_bits_override | int > 0

- name: Copy artemis.service systemd configuration
  become: true
  template:
    src: artemis.service.j2
    dest: "/etc/systemd/system/artemis.service"
    mode: "644"

- name: Enable artemis service
  become: true
  systemd:
    daemon_reload: true
    name: artemis
    enabled: true
    masked: false
