#TODO check if war is allredy present - If so fail and prompt user to use the uprade instead

- name: Download Artemis.war to {{ artemis_working_directory }}
  become: true
  get_url:
    url: "{{ artemis_war_url }}"
    dest: "{{ artemis_working_directory }}/artemis.war"
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
    mode: '0644'
  notify: restart artemis

- include_tasks: generate_ssh_keys.yml
  when:
    - version_control.localvc is defined and version_control.localvc is not none
    - version_control.localvc.ssh_key_path is defined and version_control.localvc.ssh_key_path|length > 0
    - not (only_update_artemis_config | bool)

