- name: Create artemis directory
  become: true
  file:
    path: "{{ artemis_working_directory }}"
    state: directory
    mode: '0775'

- name: Create artemis data directory
  become: true
  file:
    path: "{{ artemis_working_directory }}/data"
    state: directory
    mode: '0666'

- name: Set permissions for artemis directory
  become: true
  file:
    path: "{{ artemis_working_directory }}"
    state: directory
    recurse: yes
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  register: permissions
  notify: restart docker artemis

- name: Copy docker-compose.yml to artemis directory
  become: true
  template:
    src: "templates/docker-compose.yml.j2"
    dest: "{{ artemis_working_directory }}/docker-compose.yml"
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
    mode: 0640
  register: config
  notify: restart docker artemis

- name: Copy .env to artemis directory
  become: true
  template:
    src: "templates/.env.j2"
    dest: "{{ artemis_working_directory }}/.env"
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
    mode: 0660
  register: config
  notify: restart docker artemis

- name: Create artemis ssh key directory
  become: true
  file:
    path: "{{ artemis_ssh_key_path }}"
    state: directory
    mode: '0775'

- name: Copy ssh key
  become: true
  copy:
    content: "{{ artemis_ssh_priv_key_value }}"
    dest: "{{ artemis_ssh_key_path }}/{{ artemis_ssh_key_name }}"
  register: ssh_key
  notify: restart docker artemis

- name: Set permissions for artemis ssh key directory
  become: true
  file:
    path: "{{ artemis_ssh_key_path }}"
    state: directory
    recurse: yes
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
    mode: '0660'

- name: Copy artemis-docker.sh helper script
  become: true
  copy:
    src: files/artemis-docker.sh
    dest: "{{ artemis_working_directory }}/artemis-docker.sh"
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
    mode: 0770
  register: config
  notify: restart docker artemis


