---
- name: Check if docker is installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_installed

- name: Fail if docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed - please install docker before running this role."
  when: not docker_installed.stat.exists
