- name: Ensure artemis group {{ artemis_user_group }} exists
  become: yes
  group:
    name: "{{ artemis_user_group }}"
    gid: "{{ artemis_user_gid }}"
    state: present

- name: Ensure artemis user {{ artemis_user_name }} exists
  become: yes
  user:
    name: "{{ artemis_user_name }}"
    state: present
    uid: "{{ artemis_user_uid }}"
    group: "{{ artemis_user_group }}"
    groups: "{% if use_docker or (continuous_integration is defined and continuous_integration.localci is defined and continuous_integration.localci) %}docker{% endif %}"

- name: Ensure deployment user {{ artemis_deployment_user_name }} exists
  become: yes
  user:
    name: "{{ artemis_deployment_user_name }}"
    comment: "{{ artemis_deployment_user_comment }}"
    state: present
    uid: "{{ artemis_deployment_user_uid }}"
    group: "{{ artemis_user_group }}"
    groups: "{% if use_docker %}docker{% if else %}sudo{% endif %}"
  when: (artemis_create_deployment_user | bool)

- name: Ensure (limited) sudo privileges for user {{ artemis_deployment_user_name }}
  become: yes
  template:
    src: artemis_deployment_sudoers.j2
    dest: /etc/sudoers.d/artemis_deployment
    validate: 'visudo -cf %s'
    mode: "440"
  when:
    - artemis_create_deployment_user | bool
    - use_docker | bool

- name: Authorize ssh-key for deployment user
  become: yes
  authorized_key:
    user: "{{ artemis_deployment_user_name }}"
    state: present
    key: "{{ artemis_deployment_user_public_key }}"
  when: (artemis_create_deployment_user | bool)
