---
##############################################################################
# Check Secrets
##############################################################################

- name: Check if database password is set
  fail:
    msg: "No database password is configured!"
  when:
    - artemis_database_password is undefined or artemis_database_password is none

- name: Check if artemis_internal_admin_password is set
  fail:
    msg: "No artemis_internal_admin_password is configured!"
  when:
    - artemis_internal_admin_password is undefined or artemis_internal_admin_password is none

- name: Check if artemis_jhipster_jwt is set
  fail:
    msg: "No artemis_jhipster_jwt is configured!"
  when:
    - artemis_jhipster_jwt is undefined or artemis_jhipster_jwt is none

- name: Check if artemis_jhipster_registry_password is set
  fail:
    msg: "No artemis_jhipster_registry_password is configured!"
  when:
    - artemis_jhipster_registry_password is undefined or artemis_jhipster_registry_password is none
    - is_multinode_install|bool

##############################################################################
# Check localci Variables
##############################################################################

- name: Check if is either build_agent or core_node
  fail:
    msg: "localci configuration is incomplete - Make sure that each node is either build agent or core node"
  when:
    - continuous_integration.localci is defined
    - not continuous_integration.localci.is_core_node | default(false) and not continuous_integration.localci.is_build_agent | default(false)
- name: Check that node 1 is a core_node
  fail:
    msg: "localci configuration is incomplete - Make sure that node 1 is a core_node"
  when:
    - continuous_integration.localci is defined
    - node_id is defined and node_id == 1 and not continuous_integration.localci.is_core_node | default(false)
