---
##############################################################################
# Check Secrets
##############################################################################

- name: Check if database password is set
  fail:
    msg: "No database password is configured!"
  when:
    - artemis_database_password is undefined or artemis_database_password is none

- name: Check if artemis_internal_admin_password is set
  fail:
    msg: "No artemis_internal_admin_password is configured!"
  when:
    - artemis_internal_admin_password is undefined or artemis_internal_admin_password is none

- name: Check if artemis_ssh_priv_key_value is set
  fail:
    msg: "No artemis_ssh_priv_key_value is configured!"
  when:
    - artemis_ssh_priv_key_value is undefined or artemis_ssh_priv_key_value is none

- name: Check if artemis_jhipster_jwt is set
  fail:
    msg: "No artemis_jhipster_jwt is configured!"
  when:
    - artemis_jhipster_jwt is undefined or artemis_jhipster_jwt is none

- name: Check if artemis_jhipster_registry_password is set
  fail:
    msg: "No artemis_jhipster_registry_password is configured!"
  when:
    - artemis_jhipster_registry_password is undefined or artemis_jhipster_registry_password is none
    - is_multinode_install|bool

##############################################################################
# Check Jira Variables
##############################################################################

- name: jira variables set
  debug:
    msg: " User Management Jira Variables: {{ user_management.jira }}"
  when:
    - user_management.jira is defined

- name: Check if jira url variables is set
  fail:
    msg: "Jira configuration is incomplete - Make sure to add Jira url"
  when:
    - user_management.jira is defined
    - user_management.jira.url is undefined or user_management.jira.url is none

- name: Check if jira user variables is set
  fail:
    msg: "Jira configuration is incomplete - Make sure to add Jira user"
  when:
    - user_management.jira is defined
    - user_management.jira.user is undefined or user_management.jira.user is none

- name: Check if jira password variables is set
  fail:
    msg: "Jira configuration is incomplete - Make sure to add Jira password"
  when:
    - user_management.jira is defined
    - user_management.jira.password is undefined or user_management.jira.password is none

##############################################################################
# Check Bitbucket Variables
##############################################################################

- name: bitbucket variables set
  debug:
    msg: "Version Control bitbucket Variables: {{ version_control.bitbucket }}"
  when:
    - version_control.bitbucket is defined

- name: Check if bitbucket token variables is set
  fail:
    msg: "bitbucket configuration is incomplete - Make sure to add bitbucket token"
  when:
    - version_control.bitbucket is defined
    - version_control.bitbucket.token is undefined or version_control.bitbucket.token is none

- name: Check if bitbucket url variables is set
  fail:
    msg: "bitbucket configuration is incomplete - Make sure to add bitbucket url"
  when:
    - version_control.bitbucket is defined
    - version_control.bitbucket.url is undefined or version_control.bitbucket.url is none

- name: Check if bitbucket ssh_url variables is set
  fail:
    msg: "bitbucket configuration is incomplete - Make sure to add bitbucket ssh_url"
  when:
    - version_control.bitbucket is defined
    - version_control.bitbucket.ssh_url is undefined or version_control.bitbucket.ssh_url is none

##############################################################################
# Check bamboo Variables
##############################################################################

- name: bamboo variables set
  debug:
    msg: "Version Control bamboo Variables: {{ continuous_integration.bamboo }}"
  when:
    - continuous_integration.bamboo is defined

- name: Check if bamboo url variables is set
  fail:
    msg: "bamboo configuration is incomplete - Make sure to add bamboo url"
  when:
    - continuous_integration.bamboo is defined
    - continuous_integration.bamboo.url is undefined or continuous_integration.bamboo.url is none

- name: Check if bamboo token variables is set
  fail:
    msg: "bamboo configuration is incomplete - Make sure to add bamboo token"
  when:
    - continuous_integration.bamboo is defined
    - continuous_integration.bamboo.token is undefined or continuous_integration.bamboo.token is none

- name: Check if bamboo bitbucket_link_name variables is set
  fail:
    msg: "bamboo configuration is incomplete - Make sure to add bamboo bitbucket_link_name"
  when:
    - continuous_integration.bamboo is defined
    - continuous_integration.bamboo.bitbucket_link_name is undefined or continuous_integration.bamboo.bitbucket_link_name is none

##############################################################################
# Check localci Variables
##############################################################################

- name: Check if is either build_agent or core_node
  fail:
    msg: "localci configuration is incomplete - Make sure that each node is either build agent or core node"
  when:
    - continuous_integration.localci is defined
    - not continuous_integration.localci.is_core_node | default(false) and not continuous_integration.localci.is_build_agent | default(false)
- name: Check that node 1 is a core_node
  fail:
    msg: "localci configuration is incomplete - Make sure that node 1 is a core_node"
  when:
    - continuous_integration.localci is defined
    - node_id is defined and node_id == 1 and not continuous_integration.localci.is_core_node | default(false)

##############################################################################
# Check PostHog Variables
##############################################################################

- name: Check if posthog host is set
  fail:
    msg: "PostHog configuration is incomplete - Make sure to add PostHog host"
  when:
    - post_hog is defined
    - post_hog.host is undefined or post_hog.host is none

- name: Check if posthog token is set
  fail:
    msg: "PostHog configuration is incomplete - Make sure to add PostHog token"
  when:
    - post_hog is defined
    - post_hog.token is undefined or post_hog.token is none