---
roles:
  - src: geerlingguy.docker

  - src: geerlingguy.mysql

  - name: cloudalchemy.mysqld_exporter
    src: https://github.com/ls1admin/ansible-mysqld_exporter.git

collections:
  - name: community.mysql
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
