# Check for compatible Ansible version.
- name: Check for compatible Ansible version.
  assert:
    that: ansible_version.full is version_compare('2.16', '>=')
    msg: You need Ansible version 2.16 or higher.

# Setup nginx proxy
- include_tasks: nginx.yml

