---

- name: Setup Artemis shared storage provider
  hosts: artemis_cluster_storage

  roles:
    - role: ls1intum.artemis.storage_provider

    - role: ls1intum.artemis.firewall
      tags: firewall
      vars:
        # Management Networks - used to allow SSH / HTTP access to Hosts and services
        management_network_ipv4: "{{ firewall_management_network_ipv4 }}"
        management_network_ipv6: "{{ firewall_management_network_ipv6 }}"
        # Monitoring Service
        monitoring_host_ipv4: "{{ firewall_monitoring_host_ipv4 }}"
        monitoring_host_ipv6: "{{ firewall_monitoring_host_ipv6 }}"
