---


- name: Setup Cluster Network and NAT on Nodes
  hosts: artemis_cluster_nodes

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens18:
              addresses:
                - "{{ wireguard_host_ipv6_address }}/64"
                - "{{ host_ipv4_address }}"
              nameservers:
                addresses:
                  - "{{ dns_ipv4_address }}"
              routes:
                - to: 172.16.0.0/12
                  via: 172.24.70.254
                - to: 131.159.0.0/16
                  via: 172.24.70.254
                - to: default
                  via: 172.24.70.250
                - to: default
                  via: "fd00::ffff:1"

    - role: tomereli.proxy
      http_proxy: "http://proxy.in.tum.de:8080"
      https_proxy: "http://proxy.in.tum.de:8080"
      become: true

- name: Setup Cluster Network and Forward Proxy
  hosts: artemis_cluster:!artemis_cluster_proxy:!artemis_cluster_nodes

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens18:
              addresses:
                - "{{ wireguard_host_ipv6_address }}/64"
              dhcp4: true

    - role: tomereli.proxy
      http_proxy: "http://proxy.in.tum.de:8080"
      https_proxy: "http://proxy.in.tum.de:8080"
      become: true


- name: Setup Proxy Network
  hosts: artemis_cluster_proxy

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens18:
              dhcp4: true
              dhcp6: true
            ens19:
              addresses:
                - "{{ host_ipv4_address }}"
                - "{{ wireguard_host_ipv6_address }}/64"
