---

- name: Start Artemis service
  hosts: artemis_cluster_nodes
  serial: 1
  tasks:
    - name: Start artemis service
      become: true
      service:
        name: artemis
        state: started

    - name: Wait for 20 seconds
      pause:
        seconds: 20
