---

- name: Setup Artemis Broker and Registry
  hosts: artemis_cluster_broker

  roles:
    - role: ls1intum.artemis.broker
    - role: ls1intum.artemis.proxy
      vars:
        proxy_target_port: 8761
        proxy_generate_dh_param: false
        proxy_ssl_certificate_path: #FIXME
        proxy_ssl_certificate_key_path: #FIXME
