---
# tasks file for storage-provider

- name: Ensure group {{ artemis_group }} exists
  become: true
  group:
    name: "{{ artemis_group }}"
    gid: "{{ artemis_gid }}"
    state: present

- name: Ensure user {{ artemis_user }} exists
  become: true
  user:
    name: "{{ artemis_user }}"
    state: present
    uid: "{{ artemis_uid }}"
    group: "{{ artemis_group }}"

- name: Install NFS server
  become: true
  apt:
    name: nfs-kernel-server
    state: "present"

- name: Make sure the export exists
  become: true
  file:
    path: "{{ storage_export }}"
    state: directory
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"

- name: Configure NFS Daemon
  become: true
  template:
    src: nfs.conf.j2
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Restart nfs-server

- name: Configure export
  become: true
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Restart nfs-server
