- name: Check if broker is installed
  become: true
  stat:
    path: "{{ activemq_working_directory }}"
  register: broker_install_result

- name: Create broker in {{ activemq_working_directory }} (NOT IDEMPOTENT)
  become: true
  command: ./artemis create --user {{ activemq_username }} --password {{ activemq_password }} --require-login --force {{ activemq_working_directory }} --java-options "-Xms{{ (activemq_system_ram_proportion * ansible_memory_mb.real.total) | int }}m -Xmx{{ (activemq_system_ram_proportion * ansible_memory_mb.real.total) | int }}m"
  args:
    chdir: "{{ activemq_install_directory }}/apache-artemis-{{ activemq_version }}/bin"
  notify: restart broker
  when: not broker_install_result.stat.exists or activemq_force_reinstall

- name: Copy primary broker.xml file
  become: true
  template:
    src: activemq_primary_broker.xml.j2
    dest: "{{ activemq_working_directory }}/etc/broker.xml"
    mode: 0644
  notify: restart broker

- name: Set permissions for broker working directory
  become: true
  file:
    path: "{{ activemq_working_directory }}"
    state: directory
    recurse: yes
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  notify: restart broker

- name: Copy broker.service systemd configuration
  become: true
  template:
    src: activemq_broker.service.j2
    dest: "/etc/systemd/system/broker.service"
    mode: 0644
  notify: restart broker

- name: Ensure correct broker version is installed
  become: true
  lineinfile:
    path: "{{ activemq_working_directory }}/etc/artemis.profile"
    regexp: '^ARTEMIS_HOME='
    line: "ARTEMIS_HOME='/opt/activemq-distribution/apache-artemis-{{ activemq_version }}'"
  notify: restart broker

- name: Enable broker service
  become: true
  systemd:
    daemon_reload: yes
    name: broker
    enabled: yes
    masked: no
  notify: restart broker
