# Check secrets for broker
- include_tasks: variable_checks_broker.yml

# Create artemis user
- include_tasks: user.yml

# Install Java JDK
- include_tasks: jdk.yml

# Install ActiveMQ Broker
- include_tasks: broker.yml

# Configure ActiveMQ Broker
- include_tasks: configure.yml
