- name: Install iptables-persistent
  become: true
  apt:
    name: iptables-persistent
    state: latest
    update_cache: yes

- name: Check if docker service exists
  stat:
    path: /etc/systemd/system/docker.service.d/
  register: docker_service

- name: Copy rules.v4
  become: true
  template:
    src: rules_{{ firewall_hostgroup | default('default') }}.v4.j2
    dest: /etc/iptables/rules.v4
    mode: 0644
  register: copy4
  notify: restart docker

- name: Copy rules.v6
  become: true
  template:
    src: rules_{{ firewall_hostgroup | default('default') }}.v6.j2
    dest: /etc/iptables/rules.v6
    mode: 0644
  register: copy6
  notify: restart docker

- name: Load IPv4 rules
  become: true
  shell: "iptables-restore < /etc/iptables/rules.v4"
  changed_when: copy4.changed

- name: Load IPv6 rules
  become: true
  shell: "ip6tables-restore < /etc/iptables/rules.v6"
  changed_when: copy6.changed
