roles:
  - src: geerlingguy.docker

  - src: geerlingguy.mysql

  - name: cloudalchemy.mysqld_exporter
    src: https://github.com/ls1admin/ansible-mysqld_exporter.git

  - src: mrlesmithjr.netplan

  - src: tomereli.proxy