---
ansible_managed: "Ansible managed: Do not make changes here - they will be overwritten."

redis:
  username: artemis
  password: #FIXME
  working_directory: /opt/redis
  version: 6.2.6-v18
  port: 6379
