- name: Ensure backup location is present
  become: true
  file: 
    path: "{{ artemis_database_backup_dir }}"
    state: directory
    mode: 0755

- name: Deploy database backup script 
  become: true
  template:
    src: "templates/backup.sh.j2"
    dest: "{{ artemis_database_backup_script_path }}"
    mode: 0700

- name: Add backup cronjob
  become: true
  ansible.builtin.cron:
    name: "Backup artemis database"
    minute: "{{ artemis_database_backup_minute }}"
    hour: "{{ artemis_database_backup_hour }}"
    job: "{{ artemis_database_backup_script_path }} -dp"
