---
- name: Reload nginx
  become: true
  service:
    name: nginx
    state: reloaded

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: Apply sysctl
  become: true
  command: sysctl -p

- name: Reboot system
  become: true
  reboot:

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: true

- name: Restart nginx-health-check timer
  become: true
  systemd:
    name: nginx-health-check.timer
    state: restarted
