---
# handlers file for artemis

- name: restart artemis
  become: true
  service:
    name: artemis
    state: restarted
  when:
    - node_id is undefined
    - not artemis_force_no_restart
  listen: "restart artemis"
  throttle: 1

- name: restart artemis on node 1
  become: true
  service:
    name: artemis
    state: restarted
  when:
    - node_id is defined
    - node_id == 1
    - not artemis_force_no_restart
  listen: "restart artemis"
  throttle: 1

- name: wait for node 1 being started
  become: true
  wait_for:
    timeout: 60
  when:
    - node_id is defined
    - node_id == 1
  listen: "restart artemis"
  throttle: 1

- name: restart artemis on other nodes
  become: true
  service:
    name: artemis
    state: restarted
  when:
    - node_id is defined
    - not (node_id == 1)
    - not artemis_force_no_restart
  listen: "restart artemis"
  throttle: 1

- name: start artemis
  become: true
  service:
    name: artemis
    state: started
  listen: "start artemis"
  throttle: 1

- name: reboot system
  become: true
  reboot:

