---
# handlers file for artemis

- name: Reload apparmor profile
  become: true
  command: apparmor_parser -r /etc/apparmor.d/apparmor_profile_bubblewrap
  listen: Reload apparmor profile

- name: Restart docker compose artemis
  become: true
  shell: |
    ./artemis-docker.sh restart {{ artemis_build_version }} {{ artemis_branch }}
  args:
    chdir: "{{ artemis_working_directory }}"
  listen: "restart docker artemis"

- name: Start docker compose artemis
  become: true
  command: ./artemis-docker.sh start {{ artemis_build_version }} {{ artemis_branch }}
  args:
    chdir: "{{ artemis_working_directory }}"
  listen: "start docker artemis"
