---
hermes_version:

hermes_apns_token_key_path:

hermes_apns_team_id:

hermes_apns_key_id:

hermes_apns_token_key_content:

hermes_apns_prod_environment:

hermes_google_application_credentials_json_path:

hermes_google_application_credentials_content:

hermes_working_directory:

hermes_port:
